#+BEGIN_COMMENT
.. title: Resources
.. slug: resources
.. date: 2021-04-20 23:49:47 UTC-07:00
.. tags:
.. category:
.. link:
.. description: Resources for learning
.. type: text

#+END_COMMENT
The Resources page is here to catalogue books, articles, and videos that have been helpful to read or watch.

* Eco-region
Looking at [[http://buildsoil.net/ecoregions/][the map]] to find your eco-region. TRF is in =Marine West Coast Forest= in the Willamette Valley.
* Soil
** Ecosystem
natural plant community
Terrestrial, Palustrine, Estuarine community types
"The eyes of the future are looking back at us and praying we see beyond our own time" ~ Terry Tempest Williams
** Soil Map
We like [[https://casoilresource.lawr.ucdavis.edu/gmap/][this soil map]] for getting an idea of what soils you should expect on your property.

TRF soils are:
1. 89% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/M/MALABON.html][Malabon]]
   suborder: [[https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/class/maps/?cid=nrcs142p2_053604][Xerolls]]
   The soils formed in loamy and clayey alluvium from mixed materials. Well drained; slow runoff; moderately slow permeability. These soils have wide use for growing orchard, berry, vegetable, small grain, hay, pasture, and grass seed crops. Natural vegetation is Douglas fir, Oregon white oak, blackberry, Pacific poison-oak, other shrubs, and grasses.
2. 5% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/M/MCBEE.html][McBee]]
3. 3% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/W/WALDO.html][Waldo]]
4. 2% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/C/CHEHALIS.html][Chehalis]]
5. 1% Riverwash
** Water
[[https://apps.wrd.state.or.us/apps/wr/wr_drought/current_updates.aspx][- OR State Drought Conditions]]
- [[https://www.nrcs.usda.gov/wps/portal/nrcs/main/or/water/resources/][Hydrologic Unit Code (HUC) watersheds]] - [[https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1482458&ext=pdf][HUC 17090003 (PDF)]]
  - Average percipiatation: 39"-45"
  - The temperature regime is [[http://www.css.cornell.edu/faculty/dgr2/_static/legacy_sw/nsm/nsm_STR.html][mesic (mean annual soil temperature is 8° C or higher but lower than 15° C)]] and the moisture regime is [[http://www.css.cornell.edu/faculty/dgr2/_static/legacy_sw/nsm/nsm_SMR.html#h3_25][xeric (Mediterranean climates, where winters are moist and cool and summers are warm and dry)]].
- [[https://water.usgs.gov/lookup/getwatershed?17090003/www/cgi-bin/lookup/getwatershed][More USGS Watershed info]]
- [[https://mywaterway.epa.gov/community/170900030611/overview][TRF Watershed area]]
- [[https://www.waterqualitydata.us/provider/STORET/OREGONDEQ/OREGONDEQ-15415-ORDEQ/][Nearest monitored well]]
- Good breakdown of groundwater, aquifers, and wells [[https://pubs.usgs.gov/gip/gw_ruralhomeowner/][here]]. [[https://www.oregon.gov/OWRD/WRDPublications1/Well_Water_Handbook.pdf][Oregon well water handbook (PDF)]]
- [[https://wellwater.oregonstate.edu/][OSU - Well Water]]
*** Treating well water
Treating this on an individual-house basis is pretty straightforward:
Use an oilless compressor feeding an air stone in the bottom of the well.
Bubbles a bit of air up through the water column. That oxidizes the iron and sulfur and drops it out. Eventually the iron buildup plugs up the bottom of the well, and then you blow the well clean about every 7 years or so.
Follow that up with a water softener to take out the residual iron and manganese, as well as calcium hardness, and you end up with good tasting, clear soft water.
Ground water quality usually gets worse in the summer; more draw on the system, less flow into the aquifer.

** Weather
EQECAT - insurance brokers
* Calendar
** Plant cuttings
https://empressofdirt.net/plant-cuttings-calendar/
* Soil Health
** [[https://nph.onlinelibrary.wiley.com/doi/epdf/10.1111/nph.17306][Crop diversity enriches arbuscular mycorrhizal fungal communities in an intensive agricultural landscape]]
Paper showing the effect of polyculture cropping (compared to monoculture) on Arbuscular mycorrhizal fungi (AMF) populations.
** Compost
*** Humanure
[[https://weblife.org/humanure/pdf/humanure_handbook_third_edition.pdf][- The Humanure Handbook (PDF)]]
*** Chicken Manure
- [[https://www.extension.uidaho.edu/publishing/pdf/CIS/CIS1194.pdf][Composting and using backyard poulty water (PDF)]]

* Equipment
** Unverified Equipment
This section is for equipment we're looking at, to see if it fits our needs.
*** Tractors
[[https://www.bcsamerica.com][BCS America]] walk behind tractor and accessories
| Equipment        | Price | Link                                             | Use                                            |
| Tractor: 732     | $3100 | https://www.bcsamerica.com/product/model-732     | Driving implements around the farm             |
| Flail mower      | $2300 | https://www.bcsamerica.com/product/flail-mower   | Mowing pasture (.5-4" heights)                 |
| Sub-soiler       | $ 200 | https://www.bcsamerica.com/product/subsoiler     | Keyline ripping (water infiltration            |
| Tool carrier kit | $ 185 | https://www.bcsamerica.com/product/tool-carriers | Required for some implements (like sub-soiler) |
*** Manual well pumps
[[https://simplepump.com/][SimplePump]]:
| Equipment      | Price      | Link                                                           | Use                                     |
| Deep well pump | $1400-3625 | https://simplepump.com/our-pumps/hand-operated/deep-well-pump/ | Manual pump for wells when power is out |
[[https://www.bisonpumps.com/][Bison pump]]
| Equipment      | Price  | Link                                                                         | Use                                     |
| Deep well pump | ~$1250 | https://www.lehmans.com/product/stainless-steel-deep-well-pump-head?shopping | Manual pump for wells when power is out |
*** Solar
[[https://www.abundantsolar.com/][Abundant Solar]]
These are esimates from [[https://www.abundantsolar.com/solar-incentives/pacific-power-residential-solar-electric-incentives/][here]]:
| Power output | Price    |
|  4,200 Watt  | ~$ 9,400 |
|  7,200 Watt  | ~$12,800 |
| 10,000 Watt  | ~$17,300 |
** Verified Equipment
Equipment currently in use on the farm

** Discarded Equipment
Equipment used on the farm but ultimately discarded, with reasons why!
* Reading list
** [[https://www.pnas.org/content/114/48/E10301][Nutritional and greenhouse gas impacts of removing animals from US agriculture]]
TL;DR: Removing animals from agriculture only decreases GHG emissions 2.6% while increasing malnutrition. Focus on the big emitters: Transportation, Industrial processes, and electricity generation.

From the paper: "US agriculture was modeled to determine impacts of removing farmed animals on food supply adequacy and greenhouse gas (GHG) emissions. The modeled system without animals increased total food production (23%), altered foods available for domestic consumption, and decreased agricultural US GHGs (28%), but only reduced total US GHG by 2.6 percentage units. Compared with systems with animals, diets formulated for the US population in the plants-only systems had greater excess of dietary energy and resulted in a greater number of deficiencies in essential nutrients."
** [[https://www.hakaimagazine.com/features/thriving-together-salmon-berries-and-people/][Thriving Together: Salmon, Berries, and People]]
TL;DR: The salmonberry plant has nourished and healed Indigenous communities of the Pacific Northwest coast for countless generations, but its significance goes far beyond its value as food.
** [[https://thecounter.org/regenerative-agriculture-racial-equity-climate-change-carbon-farming-environmental-issues/][Regenerative agriculture needs a reckoning]]
TL;DR: Why avoiding uncomfortable conversations about equity, race, and access threatens to spoil a nascent movement’s environmental promise.
* Forage/Freecycle
Rooster.co (OR, CA, TX)
Craigslist
FB
FreeCycle.org

GRIN = https://www.ars-grin.gov/
gov't seed banks
