#+BEGIN_COMMENT
.. title: Resources
.. slug: resources
.. date: 2021-04-20 23:49:47 UTC-07:00
.. tags:
.. category:
.. link:
.. description: Resources for learning
.. type: text

#+END_COMMENT
The Resources page is here to catalogue books, articles, and videos that have been helpful to read or watch.

* Eco-region
Looking at [[http://buildsoil.net/ecoregions/][the map]] to find your eco-region. TRF is in =Marine West Coast Forest= in the Willamette Valley.

** Soil Map
We like [[https://casoilresource.lawr.ucdavis.edu/gmap/][this soil map]] for getting an idea of what soils you should expect on your property.

TRF soils are:
1. 89% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/M/MALABON.html][Malabon]]
   suborder: [[https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/class/maps/?cid=nrcs142p2_053604][Xerolls]]
   The soils formed in loamy and clayey alluvium from mixed materials. Well drained; slow runoff; moderately slow permeability. These soils have wide use for growing orchard, berry, vegetable, small grain, hay, pasture, and grass seed crops. Natural vegetation is Douglas fir, Oregon white oak, blackberry, Pacific poison-oak, other shrubs, and grasses.
2. 5% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/M/MCBEE.html][McBee]]
3. 3% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/W/WALDO.html][Waldo]]
4. 2% [[https://soilseries.sc.egov.usda.gov/OSD_Docs/C/CHEHALIS.html][Chehalis]]
5. 1% Riverwash

* Soil Health
** [[https://nph.onlinelibrary.wiley.com/doi/epdf/10.1111/nph.17306][Crop diversity enriches arbuscular mycorrhizal fungal communities in an intensive agricultural landscape]]
Paper showing the effect of polyculture cropping (compared to monoculture) on Arbuscular mycorrhizal fungi (AMF) populations.
** Compost
*** Humanure
[[https://weblife.org/humanure/pdf/humanure_handbook_third_edition.pdf][The Humanure Handbook]] (PDF link)
* Equipment
** Unverified Equipment
This section is for equipment we're looking at, to see if it fits our needs.
*** BCS America
https://www.bcsamerica.com/

| Equipment        | Price | Link                                             | Use                                            |
| Tractor: 732     | $3100 | https://www.bcsamerica.com/product/model-732     | Driving implements around the farm             |
| Flail mower      | $2300 | https://www.bcsamerica.com/product/flail-mower   | Mowing pasture (.5-4" heights)                 |
| Sub-soiler       | $ 200 | https://www.bcsamerica.com/product/subsoiler     | Keyline ripping (water infiltration            |
| Tool carrier kit | $ 185 | https://www.bcsamerica.com/product/tool-carriers | Required for some implements (like sub-soiler) |

** Verified Equipment
Equipment currently in use on the farm

** Discarded Equipment
Equipment used on the farm but ultimately discarded, with reasons why!
