#+BEGIN_COMMENT
.. title: First Week Down!
.. slug: first-week-down
.. date: 2021-07-13 22:44:02 UTC-07:00
.. tags:
.. category:
.. link:
.. description: First week on the property and what has been observed so far
.. type: text

#+END_COMMENT
We survived the first week!

Move in on the 6th of July went well overall. Brian came down early to help load the truck, Joey and Brenda joined later at the farm to help unload, and CD and the kids pulled their respective weight getting everything on and off the truck.

One surprise was the front storm door was propped open to help with bringing furniture in; the weight of the door was apparently too much and ripped a chunk of the door framing from around the door off the house! We propped the storm door up and I drove some long screws in along the door hinge side to provide extra support when the storm door is propped open. Not a big deal, ultimately, but also not a great start to our residence.

Otherwise, first impressions are that the sellers left the place in pretty good shape! The barn is "clean" for a barn, the cherry trees are overflowing with fruit. Apples, figs, grapes, pears and prunes are developing despite the heat extremes seen (112F the week prior!), and the house was clean and ready for move-in.


** The property

Some of the first activities on the land have been:

- learning how the irrigation well/pump work and getting the pods situated to water some of the existing trees. With as hot and dry as its been, we wanted to give the trees a little refreshment while we figured out the process.
- removed dead branches from the cherry, apple, and magnolia trees
- removed European holly and English ivy from around a hazel in the back of the pasture; removed some dead branches as well
- picked a lot of cherries and didn't make a dent in what was still on the tree!

We did a little digging in the arena to see what we'd be working with. It appears that we have about 4 inches of sand and turkey grit on top of the local clay. Maybe an inch is loose sand while the next 3 inches are hardened. I took a small hoe to that hard portion and was barely making a dent. A jackhammer bit proved more effective in breaking the hardened portion up; the bit is not friendly to manual use though! There is a pickaxe that I believe will be the nice middle ground for breaking up the hardened sand for removal.

The outstanding question is where to put it all! I believe the material will be useful for chickens and other fowl for use in their gizzards. But do we need ~150 tons of it? Perhaps a sandbox of some sort for play.

*** Morning walks

I've been walking the pasture most mornings with a hoe in hand, knocking down and shrubs or noxious weeds (like [[https://extension.oregonstate.edu/pests-weeds-diseases/weeds/tansy-ragwort][tansy ragwort]]). Occasionally one of the boys will rise and join me; that is a pleasant way to connect with them.

*** Wildlife

Surprisingly little to report! Barn swallows, little song birds like nut hatches, a red-tailed hawk and maybe a bald eagle (a nest does exist closer to the river so we assume it was). A deer or two in the morning and evenings running through the pasture.

The property is not close to running water - the Willamette is over a mile away down hill, with a busy road leading uphill to our land.

We see evidence of ground squirrel, mole, vole, or other burrowing animal. Not sure just yet which.

Insects are pretty minimal; hopefully pesticides and insecticides aren't the cause. Some hornets, lots of pollinators like bees, ants and beetles. Could probably stand to look more thoroughly though.

So far no snakes or other reptiles nor amphibians. We hope that adjusting the hydrology of the site will increase available moisture and provide some riparian-like habitat for them. The bottom of the pasture is more lush than higher parts so it seems that if we can hold more of the rains higher in the landscape, there will be more micro-climates with higher moisture available for those species that thrive there. Trees getting established will help water infiltrate deeper into the ground as well.

** The neighborhood

Met several neighbors and received some wonderful summer squash from one. I've revived the sourdough starter that has lived in the fridge the last few weeks. Cooler mornings (mid-high 50s) give me a baking window where I can offset the oven heat with outside air. Hoping to share some rounds and spread goodwill!

** The climate

We've not needed to run more than the ceiling fans with the rare exception upstairs when the boys get ready for bed. Daytime temperatures have reached the high 80s, low 90s but we have a lovely mature red maple and magnolia tree shading the western side of the house. The south side is a bit more exposed that I'd like; will look to introduce some shade there in the coming years.

The house does have [[https://www.energy.gov/energysaver/heat-pump-systems][heat pumps]] to help cool things off if necessary.

* Wrapping up

We've mostly finished unpacking; all the major elements of furniture and layout are done. Now comes decoration, unpacking suitcases, and trying to learn the new kitchen utensil layout!

All in all the move and settling in have gone as smoothly as we could have hoped. Relishing the idyllic moments watching the boys run around the property, swinging lazily in the hammock with CD, and performing small yard work and pasture tasks.

We know full well that more work is coming! We expect these first 3-5 years to be the most eventful as we establish systems of working in the garden and pasture, with an eye towards a "small efforts, consistently applied" mantra for the long term management.

Until then, we are happy making this place our home and getting settled in.
