#+BEGIN_COMMENT
.. title: The beginning
.. slug: the-beginning
.. date: 2021-04-21 00:11:53 UTC-07:00
.. tags: farm farming ag
.. category:
.. link:
.. description: The beginning of the farm journey
.. type: text

#+END_COMMENT
The beginning of our farm journey should start in July!

In the meantime, we're busy reading and planning what it is we want to do on the farm.

** Initial planning
First order of business once on the farm will be:

0. Assess the property
   a. Soil tests
   b. Infrastructure - barn, pasture fencing, gates
   c. Irrigation well and sprinkler pod system
   d. Existing tree inventory
1. Establish garden beds (possible market garden site) for fall crops
   Currently the space is a horse arena, approximately 8,000 sqft, and covered in sand, possibly crushed gravel underneath. The boys are interested in what might be the largest private sandbox! So lots of shoveling
2. Prepare southern barn stall(s) for chickens
   We'll most likely hold off on getting egg production started until the spring to avoid doing too much at the outset. However, I would like to prepare the stall(s) with laying boxes and chicken wire as appropriate.
   The chickens will also be involved in the compost production operation. The raw garden/house/yard wastes will start nearest the stall and work their way west along the inner fence until finished and carted off to the garden (maybe sold eventually). Plans to grow feed for chickens (like millet, corn, sunflower, etc) along the compost flow to minimize inputs required.
3. Woodchips and other organic matter
   Begin searching for sources of organic matter to start compost production and garden beds. These include wood chips, manure, yard and compost from neighbors.
